# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LJToolDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LJToolDemo

  pod 'SnapKit', '~> 3.2.0'
  target 'LJToolDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LJToolDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
